### ISSUE TITLE
credentials and reference to vagrant project -- please update readme

### ISSUE THREAD

**Issue by granthbr** [wstrange/openam-base-nightly#1]
This information would have saved me 30 minutes of searching the Internet....

Login to OpenAM at http://openam.example.com/openam (amadmin/password)
Login to OpenIDM at http://openidm.example.com/admin (openidm-admin/openidm-admin)
View the OpenIG landing page at http://openam.example.com/openig/
View the haproxy status page at https://openam.example.com/haproxy?stats
View the default Apache landing page at https://openam.example.com/ (Currently protected - so you will get a 403)
ssh into the guest using vagrant ssh
Using an ldap browser (Apache Directory Studio, for example) you can browse the user store at openam.example.com:389,
cn=Directory Manager / password

**Comment by wstrange** [comment]
Brandon - did you intended for this comment to be in another project?

I am in the process of moving some of the docker images - so stay tuned

**Comment by granthbr** [comment]
Warren,
No, I didn't. I haven't seen any information on how to login to the console or specific on the using the openam container. So I dug around and figured that you must have adapted this docker build from the vagrant repo I referred to in the issue. I can close it. Is there some place where you blog about setting up a docker clustered openam environment? Or is it expected that users should just figure it out (or is that what you mean by stay tuned)? 
Thanks Warren.

**Comment by wstrange** [comment]
I am in the process of moving the Docker image source over to ForgeRock's stash server. See for example
https://stash.forgerock.org/projects/DOCKER/repos/docker/browse/openidm/docker-compose.yml 

ForgeRock is still in the process of figuring out how we are going to build and distribute docker images. For now you will have to clone that directory and build your own. 

I apologize for the lack of documentation. I will try to work on some over the next couple of weeks!

**Comment by granthbr** [comment]
No need to apologize. I appreciate you building the environment.
